# Generated by Django 4.2 on 2026-02-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='Subcategory',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
