# Generated by Django 4.2 on 2026-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_product_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
