# Generated by Django 4.2 on 2026-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('message', models.TextField()),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
    ]
