# Generated by Django 4.2 on 2026-02-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_order_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_details',
            table='order_details',
        ),
    ]
