# Generated by Django 4.2 on 2026-02-25 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_payment_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment_details',
            table='payment_details',
        ),
        migrations.CreateModel(
            name='Billing_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address1', models.TextField()),
                ('pincode', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.payment_details')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.state')),
            ],
            options={
                'db_table': 'billing_detail',
            },
        ),
    ]
