# Generated by Django 4.2 on 2026-03-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_detail',
            name='payment_details',
        ),
    ]
