# Generated by Django 4.2 on 2026-03-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_shipping_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_detail',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='billing_detail',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
